// Copyright 2024 Notedown Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: extract.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingsModel int32

const (
	EmbeddingsModel_NVIDIA_EMBED_V2 EmbeddingsModel = 0
)

// Enum value maps for EmbeddingsModel.
var (
	EmbeddingsModel_name = map[int32]string{
		0: "NVIDIA_EMBED_V2",
	}
	EmbeddingsModel_value = map[string]int32{
		"NVIDIA_EMBED_V2": 0,
	}
)

func (x EmbeddingsModel) Enum() *EmbeddingsModel {
	p := new(EmbeddingsModel)
	*p = x
	return p
}

func (x EmbeddingsModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmbeddingsModel) Descriptor() protoreflect.EnumDescriptor {
	return file_extract_proto_enumTypes[0].Descriptor()
}

func (EmbeddingsModel) Type() protoreflect.EnumType {
	return &file_extract_proto_enumTypes[0]
}

func (x EmbeddingsModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmbeddingsModel.Descriptor instead.
func (EmbeddingsModel) EnumDescriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{0}
}

type SpeechToTextModel int32

const (
	SpeechToTextModel_OPENAI_WHISPER_LARGE_V3 SpeechToTextModel = 0
)

// Enum value maps for SpeechToTextModel.
var (
	SpeechToTextModel_name = map[int32]string{
		0: "OPENAI_WHISPER_LARGE_V3",
	}
	SpeechToTextModel_value = map[string]int32{
		"OPENAI_WHISPER_LARGE_V3": 0,
	}
)

func (x SpeechToTextModel) Enum() *SpeechToTextModel {
	p := new(SpeechToTextModel)
	*p = x
	return p
}

func (x SpeechToTextModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpeechToTextModel) Descriptor() protoreflect.EnumDescriptor {
	return file_extract_proto_enumTypes[1].Descriptor()
}

func (SpeechToTextModel) Type() protoreflect.EnumType {
	return &file_extract_proto_enumTypes[1]
}

func (x SpeechToTextModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpeechToTextModel.Descriptor instead.
func (SpeechToTextModel) EnumDescriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{1}
}

type Format int32

const (
	Format_ARTICLE Format = 0
	Format_VIDEO   Format = 1
	Format_PODCAST Format = 2
	Format_BOOK    Format = 3
	Format_COURSE  Format = 4
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "ARTICLE",
		1: "VIDEO",
		2: "PODCAST",
		3: "BOOK",
		4: "COURSE",
	}
	Format_value = map[string]int32{
		"ARTICLE": 0,
		"VIDEO":   1,
		"PODCAST": 2,
		"BOOK":    3,
		"COURSE":  4,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_extract_proto_enumTypes[2].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_extract_proto_enumTypes[2]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{2}
}

type ExtractArticleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ExtractArticleRequest) Reset() {
	*x = ExtractArticleRequest{}
	mi := &file_extract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractArticleRequest) ProtoMessage() {}

func (x *ExtractArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractArticleRequest.ProtoReflect.Descriptor instead.
func (*ExtractArticleRequest) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ExtractVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url               string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SpeechToTextModel SpeechToTextModel `protobuf:"varint,2,opt,name=speech_to_text_model,json=speechToTextModel,proto3,enum=extract.SpeechToTextModel" json:"speech_to_text_model,omitempty"`
}

func (x *ExtractVideoRequest) Reset() {
	*x = ExtractVideoRequest{}
	mi := &file_extract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractVideoRequest) ProtoMessage() {}

func (x *ExtractVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractVideoRequest.ProtoReflect.Descriptor instead.
func (*ExtractVideoRequest) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractVideoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtractVideoRequest) GetSpeechToTextModel() SpeechToTextModel {
	if x != nil {
		return x.SpeechToTextModel
	}
	return SpeechToTextModel_OPENAI_WHISPER_LARGE_V3
}

type ExtractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*ExtractRequest_Article
	//	*ExtractRequest_Video
	Type isExtractRequest_Type `protobuf_oneof:"type"`
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_extract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{2}
}

func (m *ExtractRequest) GetType() isExtractRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ExtractRequest) GetArticle() *ExtractArticleRequest {
	if x, ok := x.GetType().(*ExtractRequest_Article); ok {
		return x.Article
	}
	return nil
}

func (x *ExtractRequest) GetVideo() *ExtractVideoRequest {
	if x, ok := x.GetType().(*ExtractRequest_Video); ok {
		return x.Video
	}
	return nil
}

type isExtractRequest_Type interface {
	isExtractRequest_Type()
}

type ExtractRequest_Article struct {
	Article *ExtractArticleRequest `protobuf:"bytes,1,opt,name=article,proto3,oneof"`
}

type ExtractRequest_Video struct {
	Video *ExtractVideoRequest `protobuf:"bytes,2,opt,name=video,proto3,oneof"`
}

func (*ExtractRequest_Article) isExtractRequest_Type() {}

func (*ExtractRequest_Video) isExtractRequest_Type() {}

type ExtractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Format  Format `protobuf:"varint,2,opt,name=format,proto3,enum=extract.Format" json:"format,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_extract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtractResponse) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_ARTICLE
}

func (x *ExtractResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_extract_proto protoreflect.FileDescriptor

var file_extract_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x29, 0x0a, 0x15, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x74, 0x0a, 0x13, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x4b, 0x0a, 0x14,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x5f, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x54, 0x6f, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x11, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x54, 0x6f,
	0x54, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x07,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6a, 0x0a, 0x0f, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x27, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x2a, 0x26, 0x0a, 0x0f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x56, 0x49, 0x44, 0x49, 0x41, 0x5f,
	0x45, 0x4d, 0x42, 0x45, 0x44, 0x5f, 0x56, 0x32, 0x10, 0x00, 0x2a, 0x30, 0x0a, 0x11, 0x53, 0x70,
	0x65, 0x65, 0x63, 0x68, 0x54, 0x6f, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x4e, 0x41, 0x49, 0x5f, 0x57, 0x48, 0x49, 0x53, 0x50, 0x45,
	0x52, 0x5f, 0x4c, 0x41, 0x52, 0x47, 0x45, 0x5f, 0x56, 0x33, 0x10, 0x00, 0x2a, 0x43, 0x0a, 0x06,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x4f, 0x44, 0x43, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42,
	0x4f, 0x4f, 0x4b, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x55, 0x52, 0x53, 0x45, 0x10,
	0x04, 0x32, 0x49, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x3e, 0x0a, 0x07,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x8b, 0x01, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x0c, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x64, 0x6f, 0x77,
	0x6e, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x69,
	0xa2, 0x02, 0x03, 0x45, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0xca, 0x02, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0xe2, 0x02, 0x13, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x07, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_extract_proto_rawDescOnce sync.Once
	file_extract_proto_rawDescData = file_extract_proto_rawDesc
)

func file_extract_proto_rawDescGZIP() []byte {
	file_extract_proto_rawDescOnce.Do(func() {
		file_extract_proto_rawDescData = protoimpl.X.CompressGZIP(file_extract_proto_rawDescData)
	})
	return file_extract_proto_rawDescData
}

var file_extract_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_extract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_extract_proto_goTypes = []any{
	(EmbeddingsModel)(0),          // 0: extract.EmbeddingsModel
	(SpeechToTextModel)(0),        // 1: extract.SpeechToTextModel
	(Format)(0),                   // 2: extract.Format
	(*ExtractArticleRequest)(nil), // 3: extract.ExtractArticleRequest
	(*ExtractVideoRequest)(nil),   // 4: extract.ExtractVideoRequest
	(*ExtractRequest)(nil),        // 5: extract.ExtractRequest
	(*ExtractResponse)(nil),       // 6: extract.ExtractResponse
}
var file_extract_proto_depIdxs = []int32{
	1, // 0: extract.ExtractVideoRequest.speech_to_text_model:type_name -> extract.SpeechToTextModel
	3, // 1: extract.ExtractRequest.article:type_name -> extract.ExtractArticleRequest
	4, // 2: extract.ExtractRequest.video:type_name -> extract.ExtractVideoRequest
	2, // 3: extract.ExtractResponse.format:type_name -> extract.Format
	5, // 4: extract.Extract.Extract:input_type -> extract.ExtractRequest
	6, // 5: extract.Extract.Extract:output_type -> extract.ExtractResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_extract_proto_init() }
func file_extract_proto_init() {
	if File_extract_proto != nil {
		return
	}
	file_extract_proto_msgTypes[2].OneofWrappers = []any{
		(*ExtractRequest_Article)(nil),
		(*ExtractRequest_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extract_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extract_proto_goTypes,
		DependencyIndexes: file_extract_proto_depIdxs,
		EnumInfos:         file_extract_proto_enumTypes,
		MessageInfos:      file_extract_proto_msgTypes,
	}.Build()
	File_extract_proto = out.File
	file_extract_proto_rawDesc = nil
	file_extract_proto_goTypes = nil
	file_extract_proto_depIdxs = nil
}
