// Copyright 2024 Notedown Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: extract.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Extract_Extract_FullMethodName = "/extract.Extract/Extract"
)

// ExtractClient is the client API for Extract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtractClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type extractClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractClient(cc grpc.ClientConnInterface) ExtractClient {
	return &extractClient{cc}
}

func (c *extractClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, Extract_Extract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractServer is the server API for Extract service.
// All implementations should embed UnimplementedExtractServer
// for forward compatibility
type ExtractServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
}

// UnimplementedExtractServer should be embedded to have forward compatible implementations.
type UnimplementedExtractServer struct {
}

func (UnimplementedExtractServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extract not implemented")
}

// UnsafeExtractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractServer will
// result in compilation errors.
type UnsafeExtractServer interface {
	mustEmbedUnimplementedExtractServer()
}

func RegisterExtractServer(s grpc.ServiceRegistrar, srv ExtractServer) {
	s.RegisterService(&Extract_ServiceDesc, srv)
}

func _Extract_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Extract_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Extract_ServiceDesc is the grpc.ServiceDesc for Extract service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Extract_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extract.Extract",
	HandlerType: (*ExtractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _Extract_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extract.proto",
}
